### ISSUE TITLE
What time we can update version to v3.8.0 at grafana web?

### ISSUE THREAD

**Issue by X-Mars** [VolkovLabs/volkovlabs-echarts-panel#106]
Thank you.

**Comment by mikhail-vl** [comment]
@X-Mars Grafana team is on holidays since Dec, 15 and it took a while for them to review the plugin.

  They come back to me with some questions related to breaking changes we introduced. I am working with them to get it published, I will let you know when published. I expect to get and answer earlier next week.

**Comment by mikhail-vl** [comment]
@X-Mars We released a new version 4.0.0 introducing breaking changes instead of 3.8.0 and documentation updates.

  It's resubmitted to the Grafana team for review. I expect it to be reviewed later this week.
  Thank you for your contributions.

**Comment by mikhail-vl** [comment]
@X-Mars Apache ECharts 4.0.0 is available in the Grafana Catalog: https://grafana.com/grafana/plugins/volkovlabs-echarts-panel/

**Comment by X-Mars** [comment]
@mikhail-vl  I have upgraded，thanks.👍👍👍
