### ISSUE TITLE
Possibility to add support for 2gis maps

### ISSUE THREAD

**Issue by myrulezzz** [VolkovLabs/volkovlabs-echarts-panel#118]
Hi is it possible to add support in echarts library for this maps? Thanks in advance.

https://docs.2gis.com/en/mapgl/overview#nav-lvl2--Full_code_example

**Comment by mikhail-vl** [comment]
@myrulezzz I have never worked with 2gis, and I don't remember seeing a plugin for ECharts to support it.

  It may make sense to create a separate plugin for 2gis, it should be easy to do and allow to add of markers from data sources.

**Comment by myrulezzz** [comment]
Do you know any link that could help me create the connector

**Comment by mikhail-vl** [comment]
@myrulezzz I would look at the Google, Gaode, and Baidu Maps extensions for clues and do something similar. The extension interface is described in the Apache ECharts documentation.

  Also, I would ask the Apache ECharts team if they plan to add it or hear about it in their GitHub repository.
  This issue is out of the scope of the Grafana Panel. If you find an extension, we will happily support it in future releases.
