### ISSUE TITLE
Dynamic Theme Switching

### ISSUE THREAD

**Issue by yezhi780625** [VolkovLabs/volkovlabs-echarts-panel#200]
With the current options available, I can only set a single universal custom theme for all charts.

Is it possible to dynamically switch the themes of echarts based on Grafana's theme mode?

Thanks

**Comment by mikhail-vl** [comment]
@yezhi780625 You can set theme manually in the Function Code depends on the variables, selected DOM, etc.

  Theme is automatically switched if Default theme is used.
  Custom themes does not support switching automatically.

  You can update themes reacting to the Grafana Events (eventBus) for Theme Change: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/eventbus/

  Let me know if it's clear.

**Comment by yezhi780625** [comment]
@mikhail-vl  Thanks for your reply.

Based on my knowledge, to change the theme in ECharts, I need to reinitialize a new instance.  Even if a new instance is initialized with a new theme, it cannot be written back. There is no `setChart` params provided from the `option.getOption` .

Please correct me if I misunderstand.

**Comment by mikhail-vl** [comment]
@yezhi780625 You are correct, you need to reinitialize an instance to apply new theme, which happens when Grafana switch theme.

  You can call restore to re-initialize chart, but you can't override custom theme configuration:

```
chart.dispatchAction({
    type: 'restore'
});
```

  If you need dynamic custom themes, you can set color and other options directly in the returned options depending on the `theme.isDark` object.

**Comment by mikhail-vl** [comment]
@yezhi780625 Let us know if you need anything else.
