### ISSUE TITLE
Add Panel options to parse the query data as Dataset

### ISSUE THREAD

**Issue by mikhail-vl** [VolkovLabs/volkovlabs-echarts-panel#210]
The community has difficulty parsing `data` manually from the data source.
We need to find a way to make it easier and parse it automatically to a Dataset.

https://echarts.apache.org/handbook/en/concepts/dataset/

**Comment by jjspoc** [comment]
This sounds very good - many thanks for addressing the topic,  Mikhael.

I just want to share a few ideas & thoughts around this theme. Apologies upfront for the wordy message to GIT.

Viz tools like Tableau and Spotfire allow the user to drag "dimensions" around and let you drop them on the respective axes. The right thing for non programmers.

You may want to have a look at gapminder.org , in particular at this demo: https://www.gapminder.org/tools/ Hans Roslin developed the site quite a few years ago - pretty GF like I would say. He unfortunately passed away, I'm glad to see that the project is still around and apparently maintained. (The content is also great so are the talks from Hans Roslin on YT)

What if a separate "understand-data-structure" plugin parses query results (aka RefId)  and presents either code for a mapping (to be cut-n-pasted), or a view of how the data are being interpreted in order to guide the user to the required data structure - if wanted, one could add the buzz label "AI inside" to it. 

What annoys me in GF is that the user doesn't get a clue what structure data should be in (notable exception are the node Graph, where they list mandatory and optional fields. Or, why data is not parsed. That´s an issue upfront to  map() or find() for eChart, however.

Hope my comments make sense and I do hope this is the place to have that conversation. 
With best regards,

Jörg

**Comment by mikhail-vl** [comment]
@jjspoc Thanks again. As I replied in another issue. We are aiming to improve Apache ECharts user experience in the feature versions.

  You will this some of those improvements in the upcoming version.
