### ISSUE TITLE
Support for loading external resources

### ISSUE THREAD

**Issue by dyc3** [VolkovLabs/volkovlabs-echarts-panel#277]
I'm working on a fairly complex visualization using the `globe` chart type from echarts gl using some metrics from prometheus.

While playing around with the panel, I was unable to figure out how exactly to get examples like these working:
- https://echarts.apache.org/examples/en/editor.html?c=animating-contour-on-globe&gl=1
- https://echarts.apache.org/examples/en/editor.html?c=lines3d-airline-on-globe&gl=1

The first one loads d3 from a CDN and then creates the chart, and the second one loads json data from an external source and then creates the chart. 

I suppose a workaround for loading json data would be to get it fed through a data source, but this is restrictive since a panel can only query one datasource at a time.

As for loading external scripts... that could probably lead to security issues. However, it would be nice to be able to get a reference to d3 passed in to the chart options function, especially since grafana already has it available.

Would you be open to PRs for either of these?

**Comment by mikhail-vl** [comment]
@dyc3 You can select mixed data source and use as many data source as you want. I would recommend to get any data using Data Source, instead of fetching directly.

  Regarding loading external scripts, we implemented it in the Dynamic Text panel. External scripts are allowed only with sanitized mode off, per our and Grafana security requirements.

  @asimonok Should we allow external resources or there is another way?

**Comment by mikhail-vl** [comment]
We are not looking to add support for external resources in the Business Charts panel at the moment.
