### ISSUE TITLE
s.refId === "A" not detected if there is data transformed by Grafana feature

### ISSUE THREAD

**Issue by itsnull12** [VolkovLabs/volkovlabs-echarts-panel#306]
Hi VolkovLabs Team,

My data source is Loki and when I select refId == "A" it is not detected in the Business Chart Plugin if there is any Transforme the data

![Screenshot from 2024-07-06 14-20-56](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/81866625/c8b182a3-c907-4ab3-8db7-197068aa2422)

Normally, it will be detected **A:**

![Screenshot from 2024-07-06 14-30-35](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/81866625/21561148-4d2f-41b5-bc74-04a8652c62e8)

Can you help me please? Thanks!

**Comment by mikhail-vl** [comment]
@itsnull12 What Grafana version do you use? Transformations update data frames and some of them got renamed in the process.

  Does the visual editor still work?

**Comment by itsnull12** [comment]
@mikhail-vl I'm using Grafana version 11. The mode editor code and visual are not working.

As you can see in my capture, after transforming the data refId **A:** is not detected.

I have two columns, FILENAME AND COUNT ( after transforme data ) and it's still showing columns before transforme ( filename and STATUS CODE (code) )

But if you don't use data transform then **A:** is detected.

**Comment by mikhail-vl** [comment]
@itsnull12 Thank you for clarification.

@vitPinchuk Please test functionality using Transformations.

**Comment by vitPinchuk** [comment]
@itsnull12 Thank you for clarification.

When using a transformation, some transformations directly affect the data frame. The Data Frame is used to configure the panel. 

For example, I used a simple transformation.
Before transformation, I set up `Dataset Items` to `A:Category` and `A:Value`. My data received has `refId`.
Please use `console.log('context:', context)` to see all available data and options in code editor.
And my code editor and `Line Chart` works fine.   
   
  

![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/146737590/87712728-da4d-4207-b273-219ccb8eeb8b)  
  
I added a simple transformation, it doesn't change the field name, but it does change the data frame. In your example the same thing happens: when you transform the field name in some transformation, you transform the data frame as well.  

And it broke my code editor and line chart.  
  

![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/146737590/a13b7321-1999-4b26-906c-a4ad5a0b6c45)
  
  

It happens because in my options I set  `A:Category` and `A:Value`, but data frame after transformation doesn't contain `refId:A`
I need change my `Dataset Items` to available and appropriate fields. Now It works.

Please, try to use this approach for your case. It should help resolve your issue, thank you
  
  

![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/146737590/81e93c94-c7fa-419a-ba98-53bd1496d26c)

**Comment by itsnull12** [comment]
@vitPinchuk Thanks for your help, appreciate it! But what about the editor mode code ?

for instance :

context.panel.data.series.map((s) => {
  if (s.refId === "A") {
    ctg = s.fields.find((f) => f.name === "Category").values;
    vlu = s.fields.find((f) => f.name === "Value").values;
  }
});


in my case, it will showing an error "ctg is not defined"

**Comment by vitPinchuk** [comment]
@itsnull12 

Probably, you need to declare a variable. It is what I think on this part of the code 

```js
let ctg;
let vlu; 

/**
 * or
 * let ctg = []
 * let  vlu = []
 */
context.panel.data.series.map((s) => {
if (s.refId === "A") {
ctg = s.fields.find((f) => f.name === "Category").values;
vlu = s.fields.find((f) => f.name === "Value").values;
}
});
```

**Comment by itsnull12** [comment]
@vitPinchuk i see, must be declare a variable, okay vitPinchuk thank you very much!

**Comment by itsnull12** [comment]
sorry for reopen, you can mark as completed again. this is the result :

Transform data by "Group by"
Category > Group by
Qty > Calculate > Count
it will auto rename as "Qty (count)"
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/81866625/bbbf3372-70e1-4ac5-a64c-259b32b71861)


**not declare variable** (vlu is not defined)
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/81866625/5624fc56-7afd-4989-9982-81586129db6c)


**with declare variable**  (line chart not shown)
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/81866625/ab49fae5-917f-44f0-bbec-e5673f1477a0)


**the solution is, don't use "if (s.refId === "A")" and also you can remove the declaration of the variable**
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/81866625/d0d4c4d0-43c5-48ae-866c-b4a490237f57)
